### ISSUE TITLE
Add (optional) hash validation of objects

### ISSUE THREAD

**Issue by dhermes** [googleapis/google-cloud-python#15633]
- [x] Add MD5 hash check for `Download` with `stream`, `requests` only (#32)
- [ ] Add MD5 hash check for `Download` with `stream`, generic transport (i.e in `_download.py`)
- [ ] Add MD5 hash check for `Download` **without** stream
- [ ] Add MD5 hash check for `ChunkedDownload`
- [x] Add CRC32C hash check for `Download` (necessary for composite objects, though will be very slow unless `crcmod` is used with C speedups) (#135, includes warning for slow `crcmod`)
- [x] Add `Upload` hash checks (#139)

/cc @jonparrott

**Comment by parthea** [comment]
Transferring to google-cloud-python as the code for this repo will be migrated there in 1-2 weeks.

**Comment by parthea** [comment]
Closing due to inactivity.
