### ISSUE TITLE
Docs:  prepare for repo split

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-python#5912]
/cc @theacodes FYR.

Because the "documentation root" changes for inclusions between the monorepo docs build and the per-package docs build, we have to do this in two phases.

Steps before the split:
- For packages whose canonical docs are not symlinks into their own `docs/` tree, move their contents to that directory and set up symlinks.  Test that top-level docs still generate correctly via symlinks.
- For all packages, harmonize / de-duplicate their `README.rst` with the `docs/index.rst` landing page (see PR #5901 / commit 26efddf7fed57cab1148da7944f00b820f46b092 for recently-generated packages).
- If landing page is renamed (e.g. from `usage.rst` -> `index.rst`), leave behind a redirect page (see `bigquery/docs/usage.html`) and link it in `docs/conf.py`.
- Remove any generation / mutation of `README.rst` / `docs/index.rst` from `synth.py`.

GA packages:
- [x] datastore (PR #5919)
- [x] storage (PR #5923)
- [x] language (PR #5932)
- [x] spanner (PR #5938)
- [x] translate (PR #5941)
- [x] logging (PR #5943)

Beta packages:
- [x] bigquery (PR #5955)
- [x] firestore (PR #6000)
- [x] pubsub (PR #6001)
- [x] speech (PR #6017)
- [x] videointelligence (PR #6002)
- [x] vision (PR #6003)

Alpha packages:
- [x] asset (PR #5901)
- [x] automl (PR #6005)
- [x] bigquery_datatransfer (PR #6013)
- [x] bigtable (PR #6014)
- [x] container (PR #6018)
- [x] dataproc (PR #6019)
- [x] error_reporting (PR #6155)
- [x] dlp (PR #5901)
- [x] dns (PR #6020)
- [x] iot (PR #5901)
- [x] kms (PR #6021)
- [x] monitoring (PR #6156)
- [x] redis (PR #5901)
- [x] resource_manager (PR #6022)
- [x] runtimeconfig (PR #6023)
- [x] tasks (PR #5901)
- [x] texttospeech (PR #5901)
- [x] trace (PR #6024)

Not-yet-released packages:
- [x] oslogin (PR #5901)

After the split:
- Add `docs/conf.py` to all packages which don't have it (fix up bitrot for those which do).
- Add a `nox -e docs` target for all packages and test.
- Sync any redirect pages added in umbrella `docs/conf.py` with local `docs/conf.py`.

**Comment by theacodes** [comment]
Thanks for doing this, Tres. We can get started on this whenever.
