### ISSUE TITLE
Complete partial `ndb` implementations

### ISSUE THREAD

**Issue by dhermes** [googleapis/google-cloud-python#6251]
This is a list of "cleanup" I need to go back and perform for `ndb`. I am doing this for one of a few reasons:

- The feature depended on "legacy" Google App Engine features or modules (e.g. `google.appengine.api.datastore_types`)
- The class hierarchy is so intertwined that `ndb.foo.F` and `ndb.bar.G` must be implemented at the exact same time to actually perform all expected functions

----

- [ ] `query.ParameterNode.resolve()` (added in #6250)
- [ ] `query.FilterNode._to_filter()` (added in #6250)
- [ ] `query.FilterNode.__new__()` (added in #6250) handling of `isinstance(value, model.Key)` is subject to change

**Comment by averikitsch** [comment]
query.Query (added in #7239 missing `datastore_query.Order` type for orders and `QueryOptions` for default_options, as well as ancestor tests)
