### ISSUE TITLE
Firestore:  support features blacklisted in conformance tests

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-python#6533]
PR #6290 blacklisted a number of conformance tests because we do not currently support the usecases they support:

- `get-*` tests (because we use `BatchGetDocuments` API rather than the `GetDocument` API.
- `listen-*` tests exercise the "watch" features (since landed in PR #6191).
- `update_paths-*` tests (they've been excluded forever, with a note that Python lacked the support).
- Tests involving unimplemented / incorrectly implemented "transforms" (`DELETE`, `ARRAY_REMOVE`, `ARRAY_UNION`).
- `query-*` tests have been (inadvertently) skipped since being copied in from `google-cloud-common` in PR #5351).

This is a tracking issue for removing those skips / blacklist entries:

- [x] Update `Document.get` to use the `GetDocument` API, and re-enable the (one) `get-basic.textproto` test. (#6534)
- [x] Fix the support for the `DELETE` transform (one failing test) and enable those tests. (#6559)
- [x] Figure out how to support the `ARRAY_REMOVE` transform, and enable those tests. (#6651)
- [x] Figure out how to support the `ARRAY_UNION` transform, and enable those tests. (#6651)
- [x] Enable the `query-*` tests and make changes needed for them to pass. (#6839)
- [ ] Enable the `listen-*` tests and make changes needed for them to pass.

Not in scope:

~~- Figure how to support the "update with paths" use case, and enable those tests.~~

**Comment by tseaver** [comment]
Note:  by my read of the spec document, we do not need to support the `update-paths-*` cases:  they are for an alternative spelling of `Document.update` in languages which cannot use objects (such as `FieldPath` instances) as map keys.
