### ISSUE TITLE
Storage: HMAC Service Account key support

### ISSUE THREAD

**Issue by jkwlui** [googleapis/google-cloud-python#7851]
(@tseaver) Working from the internal support request / user guide, steps are:

- [x] Add class `google.cloud.storage.hmac.HMACKeyMetadata` (representing resource returned from create / get / list operations, and passed to update).  Holds reference to a client, and maps resource entities onto properties. (#8041)
- [x] Add `Client.create_hmac_key` method, taking `service_account_email` and returning a tuple, `(metadata, secret)`, where `metadata` is an `HMACKeyMetadata` instance and `secret` is the bytes returned by the `hmacKeys.create` API. (#8043)
- [x] Add `Client.list_hmac_keys` method, taking optional `service_account_email`, `max_results`, and `show_deleted_keys`, and  returning an iterator whose items are `HMACKeyMetadata` instances. (#8043)
- [x] Add `HMACKeyMetadata.exists` method. (#8045)
- [x] Add `HMACKeyMetadata.reload` method. (#8045)
- [x] Add `HMACKeyMetadata.update` method, pushing the current value of the `HMACKeyMetadata.state` property. (#8045)
- [x] Add `HMACKeyMetadata.delete` method. (#8045)
- [ ] Add system tests exercising the CRUD cycle.

**Comment by tseaver** [comment]
@jkwlui I don't have any context for this feature request:  can you please provide a pointer to a design doc / specification?

**Comment by sangramql** [comment]
looks like CRUD tests already added by @tseaver .

<img width="1440" alt="Screen Shot 2019-07-02 at 9 43 56 PM" src="https://user-images.githubusercontent.com/39852271/60615203-38112080-9dec-11e9-895e-7b8161805fc6.png">

**Comment by tseaver** [comment]
@sangramql All the work for this issue is on the `storage-add-hmac-key-support-feature` (PR #8430), whose merge is pending approval from @jkwlui that the feature is reading for non-whitelisted use on the production backend.

**Comment by sangramql** [comment]
Got it. Thank you @tseaver
