### ISSUE TITLE
Release the world to support 'client_info' for manual clients.

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-python#7968]
/cc @crwilcox, @busunkim96, @tswast 

Follow-on to #7825.  Because we are releasing new features in `google-api-core` and (more importantly) `google-cloud-core`, we need to handle this release phase delicately.  Current clients which depend on `google-cloud-core` use a too-narrow pin:

```bash
$ grep google-cloud-core */setup.py | grep -v "^core"
bigquery/setup.py:    "google-cloud-core >= 0.29.0, < 0.30dev",
bigtable/setup.py:    'google-cloud-core >= 0.29.0, < 0.30dev',
datastore/setup.py:    'google-cloud-core >=0.29.0, <0.30dev',
dns/setup.py:    'google-cloud-core >= 0.29.0, < 0.30dev',
firestore/setup.py:    'google-cloud-core >= 0.29.0, < 0.30dev',
logging/setup.py:    'google-cloud-core >= 0.29.0, < 0.30dev',
resource_manager/setup.py:    'google-cloud-core >= 0.29.0, < 0.30dev',
runtimeconfig/setup.py:    'google-cloud-core >= 0.29.0, < 0.30dev',
spanner/setup.py:    'google-cloud-core >= 0.29.0, < 0.30dev',
storage/setup.py:    'google-cloud-core >= 0.29.0, < 0.30dev',
trace/setup.py:    'google-cloud-core >=0.29.0, <0.30dev',
translate/setup.py:    'google-cloud-core >= 0.29.0, < 0.30dev',
```

Per conversation today, we plan to go ahead and release a `1.0.0` of `google-cloud-core`.  *Before* that, we need to make releases from the last tags of the clients above which broaden the range to `google-cloud-core >= 0.29.0, < 2.0dev`.

### Prep Releases

For each of the following:

- [x] `bigquery` (#7969)
- [x] `bigtable` (#7970)
- [x] `datastore` (#7971)
- [x] `dns` (#7972)
- [x] `firestore` (#7973)
- [x] `logging` (#7974)
- [x] `resource_manager` (#7975)
- [x] `runtimeconfig` (#7976)
- [x] `spanner` (#7977)
- [x] `storage` (#7978)
- [x] `trace` (#7979)
- [x] `translate` (#7980)

the procedure is:

- Make a "release branch" from the last tag, e.g. `$ git checkout -b bigquery-1.11-back bigquery-1.11.2`.
- Push that branch to upstream, e.g. `$ git push upstream bigquery-1.11-back`.
- Make a branch from that branch, e.g. `$ git checkout -b bigquery-1.11.3-release bigquery-1.11-back`.
- Update the pin in `setup.py` to `google-cloud-core >= 0.29.0, < 2.0dev`.
- Commit the change, e.g. `$ git commit setup.py -m "Widen range for 'google-cloud-core'."`
- Push the `-release` branch, e.g. `$ git push origin bigquery-1.11.3-release`.
- Make a PR for the `-release` branch, targeting the `-back` branch.
- Label the PR `autorelease-pending`.
- Edit `setup.py` to bump the version, e.g. to `1.11.3`.
- Edit `CHANGELOG.md` to include the widening and PR #.
- Push those changes to the `origin` branch.
- Merge the PR after CI.
- Update the local branch, e.g. `$ git checkout bigquery-1.11-back && git fetch upstream && git merge upstream/bigquery-1.11-back`.
- Tag the local branch, e.g. `$ git tag bigquery-1.11.3`
- Push the tag, e.g.: `$ git push upstream bigquery-1.11.3`.
- Monitor the PR to see that the bot updates the tags and makes / releases artifacts. **Note:  I had to do the release tagging / push to PyPI bits manually.**

### Core Releases

Once all the prep releases are finished, use `releasetool` to make new releases of core packages:

- [x] `api_core-1.11.0` (#7985)
- [x] Update `core/setup.py` to pin `google-api-core >= 1.11.0, < 2.0dev`. (#7986)
- [x] `core-1.0.0` (#7990)

### Update Client Library Pins

Once the new `google-api-core` and `google-cloud-core` releases are complete, create PRs for each client from `master` which bump the pins for each one accordingly to match:

- [x] `bigquery` (#7993)
- [x] `bigtable` (#7993)
- [x] `datastore` (#7993)
- [x] `dns` (#7993)
- ~~`error_reporting` not needed, it doesn't directly depend on `google-api-core` / `google-cloud-core`~~
- [x] `firestore` (#7993)
- [x] `logging` (#7993)
- [x] `resource_manager` (#7993)
- [x] `runtimeconfig` (#7993)
- [x] `spanner` (#7993)
- [x] `storage` (#7993)
- [x] `trace` (#7993)
- [x] `translate` (#7993)

### Client Library Releases

After merging the "update pins" PRs, run `releasetool` for each manual client, and shepherd out the releases:

- [x] `bigquery` (#8001)
- [x] `bigtable` (#8002)
- ~~`datastore` does not yet have `client_info` support!  See issue #8003.~~ 
- [x] `dns` (#8004)
- [x] `firestore` (#8005)
- [x] `logging` (#8006)
- [x] `resource_manager` (#8007)
- [x] `runtimeconfig` (#8008)
- [x] `spanner` (#8009)
- [x] `storage` (#8010)
- [x] `trace` (#8011)
- [x] `translate` (#8012)

Because `error_reporting` relies on transitive deps of `google-cloud-logging` to pick up new `google-api-core` and `google-cloud-core` versions, it has to be handled specially:

- [x] Pin its dependency `google-cloud-logging >= 1.11.0`. (#8015)
- [x] Release it. (#8019)

Datastore:

- [x] Actually implement the `client_info` feature. (#8013)
- [x] Release it. (#8020)

**Comment by tseaver** [comment]
Whew!
