### ISSUE TITLE
Add `client_options` to constructors for manual clients.

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-cloud-python#8475]
*List of clients is copied from the issue for client_info. See #7825.*

The client_options constructor argument provides a consistent way for options to be set on clients. Currently only API Endpoint can be set with client_options.

GAPIC clients will gets this change via the generator, but the clients below need to be updated manually.

Clients that need client_options:

- [x] BigQuery #8999 
- [x] Bigtable #9517
  - [x] data endpoint
  - [x] admin endpoint
- [x] Datastore #9055
- [x] DNS #9516
- [x] Error Reporting  #9152
- [x]  Firestore (and Firestore Beta) #9048
- [x]  Logging #9046
- [x]  Pub/Sub ([Publisher](https://github.com/googleapis/google-cloud-python/blob/master/pubsub/google/cloud/pubsub_v1/publisher/client.py), [Subscriber](https://github.com/googleapis/google-cloud-python/blob/master/pubsub/google/cloud/pubsub_v1/subscriber/client.py#L43)) (done via `**kwargs`) 
- [x]  Resource Manager #9043
- [x]  Runtime Config #9045
- [x]  Spanner #9151
    - [x] Client.instance_admin_api
    - [x] Client.database_admin_api
    - [x] Database.spanner_api
- [x] Storage #9054
- [x] Trace and Trace V1 #9154
- [x] Translate (no GRPC version needed, because v3beta1 is pure-autogen) #8737

**Comment by sduskis** [comment]
Cloud Bigtable (and maybe others) will need two different `client_options`, since it has a data and admin endpoint.

**Comment by tseaver** [comment]
Spanner has three, accessed via:  `Client.instance_admin_api`, `Client.database_admin_api`, `Database.spanner_api`.
