### ISSUE TITLE
Docs: Migrate to googleapis.dev

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-cloud-python#8704]
- [x] All APIs have published documentation at googleapis.dev
- [x] READMEs reference googleapis.dev documentation (not googleapis.github.io) #8705 
- [x] docs/conf.py files use googleapis.dev `objects.inv` #9085 
- [x] Activate redirects to googleapis.dev #9080

**Comment by ashb** [comment]
Is a single objects.inv not published anywhere anymore? We used this a lot in the Airflow docs from the various GCP hooks and operators.

**Comment by busunkim96** [comment]
@ashb, unfortunately there won't be a single objects.inv. Since the documentation is being published separately, each package has their own objects.inv.

`https://googleapis.dev/python/google-api-core/latest/objects.inv` will have all the objects for the package `google-api-core`. That will cover anything under `google.api_core`

Each of the package READMEs has links to the documentation. If you can give me a list of packages airflow references in the documentation, I'd also be happy to compile the list for you.

Thanks for your patience as we move our documentation around. :)

**Comment by TobKed** [comment]
Hi @busunkim96. Thank you for information! 
Recently was published updated documentation about GCP integration in Airflow:
https://airflow.readthedocs.io/en/latest/integration.html#gcp-google-cloud-platform
If it is be possible to generate list for these libraries and also for those which are not integrated yet it would be very, very helpful.

**Comment by busunkim96** [comment]
@TobKed This is the full list:

```
{
    "google-api-core": "https://googleapis.dev/python/google-api-core/latest",
    "google-cloud-asset": "https://googleapis.dev/python/cloudasset/latest",
    "google-cloud-automl": "https://googleapis.dev/python/automl/latest",
    "google-cloud-bigquery": "https://googleapis.dev/python/bigquery/latest",
    "google-cloud-bigquery-datatransfer": "https://googleapis.dev/python/bigquerydatatransfer/latest",
    "google-cloud-bigquery-storage": "https://googleapis.dev/python/bigquerystorage/latest",
    "google-cloud-bigtable": "https://googleapis.dev/python/bigtable/latest",
    "google-cloud-container": "https://googleapis.dev/python/container/latest",
    "google-cloud-containeranalysis": "https://googleapis.dev/python/containeranalysis/latest",
    "google-cloud-core": "https://googleapis.dev/python/google-cloud-core/latest",
    "google-cloud-datacatalog": "https://googleapis.dev/python/datacatalog/latest",
    "google-cloud-datalabeling": "https://googleapis.dev/python/datalabeling/latest",
    "google-cloud-dataproc": "https://googleapis.dev/python/dataproc/latest",
    "google-cloud-datastore": "https://googleapis.dev/python/datastore/latest",
    "google-cloud-dlp": "https://googleapis.dev/python/dlp/latest",
    "google-cloud-dns": "https://googleapis.dev/python/dns/latest",
    "google-cloud-error-reporting": "https://googleapis.dev/python/clouderrorreporting/latest",
    "google-cloud-firestore": "https://googleapis.dev/python/firestore/latest",
    "google-cloud-iam": "https://googleapis.dev/python/iamcredentials/latest",
    "google-cloud-iot": "https://googleapis.dev/python/iot/latest",
    "google-cloud-irm": "https://googleapis.dev/python/irm/latest",
    "google-cloud-kms": "https://googleapis.dev/python/cloudkms/latest",
    "google-cloud-language": "https://googleapis.dev/python/language/latest",
    "google-cloud-logging": "https://googleapis.dev/python/logging/latest",
    "google-cloud-monitoring": "https://googleapis.dev/python/monitoring/latest",
    "google-cloud-os-login": "https://googleapis.dev/python/oslogin/latest",
    "google-cloud-phishingprotection": "https://googleapis.dev/python/phishingprotection/latest",
    "google-cloud-pubsub": "https://googleapis.dev/python/pubsub/latest",
    "google-cloud-redis": "https://googleapis.dev/python/redis/latest",
    "google-cloud-resource-manager": "https://googleapis.dev/python/cloudresourcemanager/latest",
    "google-cloud-runtimeconfig": "https://googleapis.dev/python/runtimeconfig/latest",
    "google-cloud-scheduler": "https://googleapis.dev/python/cloudscheduler/latest",
    "google-cloud-securitycenter": "https://googleapis.dev/python/securitycenter/latest",
    "google-cloud-spanner": "https://googleapis.dev/python/spanner/latest",
    "google-cloud-speech": "https://googleapis.dev/python/speech/latest",
    "google-cloud-storage": "https://googleapis.dev/python/storage/latest",
    "google-cloud-talent": "https://googleapis.dev/python/talent/latest",
    "google-cloud-tasks": "https://googleapis.dev/python/cloudtasks/latest",
    "google-cloud-texttospeech": "https://googleapis.dev/python/texttospeech/latest",
    "google-cloud-trace": "https://googleapis.dev/python/cloudtrace/latest",
    "google-cloud-translate": "https://googleapis.dev/python/translation/latest",
    "google-cloud-videointelligence": "https://googleapis.dev/python/videointelligence/latest",
    "google-cloud-vision": "https://googleapis.dev/python/vision/latest",
    "google-cloud-webrisk": "https://googleapis.dev/python/webrisk/latest",
    "google-cloud-websecurityscanner": "https://googleapis.dev/python/websecurityscanner/latest",
    "grafeas": "https://googleapis.dev/python/grafeas/latest"
}
```

**Comment by TobKed** [comment]
Thank you very much @busunkim96. Great job!
